### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [faizaanceg/avar#1]
Use of `'$1^'` inside queries is quite pointless, and even dangerous.

You should use either `$1` for proper escaping, or `$1^` when no escaping is needed ;)

Although you use it with `LIKE '$1^'`, in this example it is better to use `LIKE $1`

Also, see this comment: https://github.com/vitaly-t/pg-promise-demo/blob/master/db/index.js#L7

plus this one: https://github.com/vitaly-t/pg-promise-demo/blob/master/db/index.js#L22

**Comment by aulisius** [comment]
Hey! Thanks for the feedback =) 

First of all, pg-promise is a really cool library :D 

I didn't know about the `extend` and `require` thing. Thanks for pointing that out.

The reason I used `'$1^'` was because `$1` wasn't initially working for me. It works now. Weird :/

Anyway, fixed them :+1:
